### ISSUE TITLE
Todoist checkboxes are not being styled properly

### ISSUE THREAD

**Issue by dirkschut** [jamiebrynes7/clair-de-lune-obsidian-theme#2]
![image](https://user-images.githubusercontent.com/1783781/97023304-9750f200-1555-11eb-84f8-4d84372ba3cb.png)

As you can see the checkboxes are not being styled properly (made into a circle and coloured).

I'm running the theme without any custom modifications, todoist plugin v 1.4 and obsidian 0.9.4 on windows 10.

**Comment by jamiebrynes7** [comment]
That is strange, it works fine for me (with the exact same setup), can you open up the dev tools and select one of the input elements and take a screenshot of the 'Styles' tab? 

I.e. - 

![image](https://user-images.githubusercontent.com/13353733/97024991-666dbe80-154f-11eb-92df-52f306039d05.png)

**Comment by dirkschut** [comment]
![image](https://user-images.githubusercontent.com/1783781/97040814-d50e4480-156e-11eb-913c-6c48db32c327.png)

**Comment by dirkschut** [comment]
I think this might be the problem. Testing now.

```css
input[type="checkbox"]{
  -webkit-appearance: checkbox;
}

**Comment by dirkschut** [comment]
adding this to the bottom of the theme fixed it for me:

``` css

input[type="checkbox"]{
  -webkit-appearance: inherit !important;
}

**Comment by jamiebrynes7** [comment]
Thanks for doing the debugging on this one for me! Will be fixed in #4 😀

**Comment by jamiebrynes7** [comment]
Incidentally I ran into this on my laptop, but not my desktop. Not entirely sure why it only _sometimes_ happens

**Comment by dirkschut** [comment]
> Incidentally I ran into this on my laptop, but not my desktop. Not entirely sure why it only _sometimes_ happens

There are two things I think could be found on here. The first is that you could be using a dev version on your PC and a production version on your laptop.

The second thing could be, and I don't have any electron knowledge so this is all hypothesis, that for some reason either your laptop or your PC has obsidian using an older electron version (or an older version of an electron dependency).
