### ISSUE TITLE
Feature Request: Make font size for editor and preview modes based on variable

### ISSUE THREAD

**Issue by greenmanspirit** [jamiebrynes7/clair-de-lune-obsidian-theme#26]
Hello, I really enjoy this theme. In order to make it usable on my small laptop screen, I had to go through and up the size of the fonts. I intend to keep using this theme so I will end up doing this for every update. I was wondering if you could make it so the font sizes are variables at the top of the file in :root so they could easily be customized by users.

Thanks!

**Comment by jamiebrynes7** [comment]
All font sizes used in the theme should now be controllable by CSS variables after #27

**Comment by greenmanspirit** [comment]
Thank you!

**Comment by jamiebrynes7** [comment]
Released in [v1.3](https://github.com/jamiebrynes7/clair-de-lune-obsidian-theme/releases/tag/v1.3)!
