### ISSUE TITLE
Consider changing the name of the theme

### ISSUE THREAD

**Issue by inputsh** [jamiebrynes7/clair-de-lune-obsidian-theme#3]
I understand your theme is based off of VS Code's Moonlight theme, but there's already a Moonlight theme in Obsidian's community themes: https://github.com/kartik-karz/moonlight-obsidian

I don't know why yours isn't in there or whether you have desire to distribute your theme through Obsidian's community themes, but having two of them named the same definitely lead to at least one person being confused.

Pinging @kartik-karz as well so that you two will hopefully reach an agreement on how to solve this name conflict.

**Comment by jamiebrynes7** [comment]
Ah shoot, I checked the forums before choosing the name, but didn't search in the community themes tab.

I'm happy to change the name to disambiguate the themes.

**Comment by jamiebrynes7** [comment]
All done and renamed! 😃
