### ISSUE TITLE
H1, H2 fluid on preview

### ISSUE THREAD

**Issue by mafsi** [jamiebrynes7/clair-de-lune-obsidian-theme#34]
# Rendering long lines in H1 & H2
There is a bug in rendering long titles in preview.

![h1 without display_block](https://user-images.githubusercontent.com/61430691/100493755-d5d46080-3142-11eb-93c9-d0390a4d018b.gif)

# Solving
Adding a `display:block` will solve the problem 726956c7cd0b7e00e66851a074a0252e014e1163

## Results
![h1 with display_block](https://user-images.githubusercontent.com/61430691/100493803-7f1b5680-3143-11eb-8e4e-bb4c92ab857b.gif)

**Comment by jamiebrynes7** [comment]
Yup I can reproduce this, this is actually related to the italics in the title as the DOM rendered doesn't play nicely with the changes in https://github.com/jamiebrynes7/clair-de-lune-obsidian-theme/pull/21
