### ISSUE TITLE
Task checkmarks in embedded notes cut off

### ISSUE THREAD

**Issue by aventuraviper** [jamiebrynes7/clair-de-lune-obsidian-theme#38]
When embedding a note that has a list of tasks, the check circles are cut-off midway
![image](https://user-images.githubusercontent.com/55485055/110814239-2a7a9200-8281-11eb-8098-075be9d1f4f5.png)

**Comment by jamiebrynes7** [comment]
Yup, it looks like the formatting on tasks lists are slightly off (I never noticed as I use https://github.com/jamiebrynes7/obsidian-todoist-plugin for all my tasks).

**Comment by aventuraviper** [comment]
Thanks for the fix - looks much neater now :)

P.S. I was using your todoist plugin, which is how I came across the theme, until I decided todoist makes some odd choices. Still really enjoy the  theme though!
