### ISSUE TITLE
Increasing the width of the main container in the editor mode

### ISSUE THREAD

**Issue by vijo** [jamiebrynes7/clair-de-lune-obsidian-theme#48]
How can I increase the width of the main writing area in the editor. I have tried a number of things but nothing seems to be working. The margins are too large for me and the writing area becomes too small.

**Comment by jamiebrynes7** [comment]
Is 'Readable line length' turned on in your settings? Under the 'Editor' tab? 

This theme doesn't constrain the width of the editing panel itself.
