### ISSUE TITLE
Feature request: Add formatting for comments

### ISSUE THREAD

**Issue by duckste** [jamiebrynes7/clair-de-lune-obsidian-theme#49]
Hello, really like this theme.
May you please integrate formattings for comments? Right now, MD comments looks in edit mode just like normal plain text.
It would be nice to see at one sight, that there is difference.
![grafik](https://user-images.githubusercontent.com/91777649/135708826-f72f8d51-1dbf-4824-a6a8-1ddebbb7f4db.png)

Thanks and have a great day
dueckste

**Comment by jamiebrynes7** [comment]
Fixed in https://github.com/jamiebrynes7/clair-de-lune-obsidian-theme/commit/5e6ec387cdea472cfd5506f9e15705ed2c91f6ce and released in [v1.5.2](https://github.com/jamiebrynes7/clair-de-lune-obsidian-theme/releases/tag/v1.5.2).
