### ISSUE TITLE
Icons in dropdown entries causing text misalignment

### ISSUE THREAD

**Issue by auxbuss** [jamiebrynes7/clair-de-lune-obsidian-theme#50]
If you pin an item in, say, the Command Palette, the pin icon is overwritten by the text.
<img width="695" alt="Screenshot 2021-10-11 at 13 46 45" src="https://user-images.githubusercontent.com/82220/136798557-87042195-8375-4f72-83b2-4b421bca806a.png">
The same behaviour occurs in, for example, the Admonition plug-in dialogue:
<img width="546" alt="Screenshot 2021-10-11 at 14 24 13" src="https://user-images.githubusercontent.com/82220/136798831-6a7009bc-dcf5-40a5-a85e-5d65cb77a33b.png">

**Comment by auxbuss** [comment]
Ah, there's a PR waiting to be merged that fixes the first https://github.com/jamiebrynes7/clair-de-lune-obsidian-theme/pull/46. I've added a comment to the PR to fix the second.

**Comment by jamiebrynes7** [comment]
Fixed in https://github.com/jamiebrynes7/clair-de-lune-obsidian-theme/commit/1840236d2f0e7ed7a9a3a66f98341f16164b325b and released in [v1.5.2](https://github.com/jamiebrynes7/clair-de-lune-obsidian-theme/releases/tag/v1.5.2).
