### ISSUE TITLE
Selecting a code segment is not highlighted correctly

### ISSUE THREAD

**Issue by Syphdias** [jamiebrynes7/clair-de-lune-obsidian-theme#52]
![image](https://user-images.githubusercontent.com/16988672/145274708-cf12476b-75d2-4de9-91cb-025f4bc0e6a8.png)

**Comment by jamiebrynes7** [comment]
Hey, this is consistent with the default themes which display the same behaviour. E.g. - 

![image](https://user-images.githubusercontent.com/13353733/148558251-e2e5e02c-5e50-42ce-8055-631208e0ee2d.png)

From what I can tell, there isn't a straightforward solution for this.
