### ISSUE TITLE
Weird spacing when collapsing list items with inline code.

### ISSUE THREAD

**Issue by inputsh** [jamiebrynes7/clair-de-lune-obsidian-theme#9]
Steps to reproduce:

```
- `p` to list the current partition table.
    - Some sub-item
```

Now collapse the line that starts with `p` in the editor mode.

When it's not collapsed, everything looks fine:

![Screenshot from 2020-10-26 08-47-10](https://user-images.githubusercontent.com/4890548/97146287-e1a9bd00-1767-11eb-9ff1-1fd08b3ba0c2.png)

...but when you collapse that line, there's a weird spacing between ticks (`) and what's written within them:

![Screenshot from 2020-10-26 08-45-22](https://user-images.githubusercontent.com/4890548/97146189-b7f09600-1767-11eb-9be3-d2098f550d79.png)

The only modification I've made to the theme is the font I'm using, so I believe you should be able to reproduce it.

**Comment by jamiebrynes7** [comment]
Huh, this is a weird one, based on the Chrome Dev Tools this looks like a bug from the default `app.css`, but I think I can patch it in the theme, I'll report this upstream as well 😄 

With default dark theme:

![image](https://user-images.githubusercontent.com/13353733/97215212-1182b000-17bc-11eb-9f83-0803f391f210.png)


![image](https://user-images.githubusercontent.com/13353733/97215187-0af43880-17bc-11eb-9ecd-ba702267d34a.png)

**Comment by jamiebrynes7** [comment]
[Upstream bug report](https://forum.obsidian.md/t/collapsed-code-block-in-list-causes-additional-padding-in-inline-code-elements-in-parent-block/7633)
